name: start_cooking
description: A Filipino recipe app with AI-powered food scanning capabilities.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6

  # HTTP and networking
  http: ^1.1.0
  shared_preferences: ^2.2.2

  # Camera and permissions
  camera: ^0.10.5+5
  permission_handler: ^11.2.0

  # Image processing
  image_picker: ^1.0.4
  
  # Time formatting
  timeago: ^3.6.0
  
  # Real-time communication
  socket_io_client: ^2.0.3+1
  
  # Loading animations
  shimmer: ^3.0.0
  
  # Dialog and alert libraries
  rflutter_alert: ^2.0.7
  awesome_dialog: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # App assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/ingredients/
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/images/image6.png
    - assets/images/image7.png
    - assets/images/image8.png
    - assets/images/image9.png
    - assets/images/image10.png
    - assets/images/image11.png
    - assets/images/image12.png
    - assets/images/image13.png
    - assets/images/logo.png
  
  # App fonts (optional - uncomment if you want custom fonts)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700